export const SELECT_CREATE_TYPE = "SELECT_CREATE_TYPE";

export const UPDATE_IMAGE_URI = "UPDATE_IMAGE_URI";

export const UPDATE_MOCKUP_URI = "UPDATE_MOCKUP_URI";

export const SAVE_USER_DATA = "SAVE_USER_DATA";

export const SAVE_USER_PRODUCT = "SAVE_USER_PRODUCT";

export const SAVE_MATERIAL_OPTION = "SAVE_MATERIAL_OPTION";

export const SAVE_PRINT_OPTION = "SAVE_PRINT_OPTION";

export const SAVE_COLOR_OPTION = "SAVE_COLOR_OPTION";

export const SAVE_SIZE_OPTION = "SAVE_SIZE_OPTION";

export const SAVE_PRODUCT_FRONT = "SAVE_PRODUCT_FRONT";

export const SAVE_PRODUCT_BACK = "SAVE_PRODUCT_BACK";

export const SAVE_PRODUCT_NAME = "SAVE_PRODUCT_NAME";

export const SAVE_PRODUCT_DESCRIPTION = "SAVE_PRODUCT_DESCRIPTION";

export const SAVE_PRODUCT_PRICE = "SAVE_PRODUCT_PRICE";

export const SAVE_PRODUCT_ORDER = "SAVE_PRODUCT_ORDER";

export const SAVE_ORDER = "SAVE_ORDER";

export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const UPDATE_USER_LIKES = "UPDATE_USER_LIKES";

export const UPDATE_USERS = "UPDATE_USERS";

export const SAVE_EDIT_IMAGE = "SAVE_EDIT_IMAGE";

export const UPDATE_CURRENT_EDIT_IMAGE = "UPDATE_CURRENT_EDIT_IMAGE";

export const SAVE_ORIGINAL_FRONT_URI = "SAVE_ORIGINAL_FRONT_URI";

export const SAVE_ORIGINAL_BACK_URI = "SAVE_ORIGINAL_BACK_URI";
